fix(inheritance): Add elements not found in schema
ladybug-tools/pydantic-openapi-helper pull request #83
Opened 2021-05-14 22:41 UTC by tymokvo

Re: pollination/pollination-server#194

The `RoleEnum` is not found from the call to `pydantic.schema.schema` and thus isn't added to the `enums` dictionary by the loop on line 320 in `inheritance.py`. This adds the missing elements to the `enums` dictionary.

I've tested this interactively against `pollination-server`. The generated JSONs with this change are [here](https://storage.cloud.google.com/lbt-blobs/misc-dev-blobs/pydantic-openapi-helper/openapi_mapper.json). I'm not sure if this is how it needs to work for C# code generation necessarily, though.

2021-05-15 11:10 UTC, mostaphaRoudsari approved these changes
It looks good to me but @MingboPeng should test the generated OpenAPI files before we merge this in.

2021-05-15 11:10 UTC, mostaphaRoudsari commented on pydantic_openapi_helper/inheritance.py
> +                     v in mapper.items() if k not in schemas.keys()}
This is probably more 'pythonic'!

```suggestion
    missing_items = {k: v for k,
                     v in mapper.items() if k not in schemas}
```

2021-05-17 17:43 UTC, tymokvo commented
@MingboPeng let me know if you need anything from me to test this

2021-05-18 23:59 UTC, mostaphaRoudsari commented
I added @MingboPeng as a reviewer so it pops up on his GitHub page!

2021-05-19 00:20 UTC, MingboPeng commented
Hi @tymokvo, I don't have access to: https://storage.cloud.google.com/lbt-blobs/misc-dev-blobs/pydantic-openapi-helper/openapi_mapper.json
![image](https://user-images.githubusercontent.com/9031066/118738986-503e8d00-b816-11eb-8ca5-8bdc46342379.png)

Meanwhile, could you also please provide me the openapi_inheritance.json as well?

2021-05-19 00:22 UTC, MingboPeng commented
Nevermind, I found them from Google Cloud

2021-05-19 00:36 UTC, MingboPeng commented
openapi_inheritance.json still doesn't include **RoleEnum**
![image](https://user-images.githubusercontent.com/9031066/118739905-9563be80-b818-11eb-8e13-8f61d0ff78d3.png)

enums in mapper.json are duplicated:
![image](https://user-images.githubusercontent.com/9031066/118739311-2a65b800-b817-11eb-91ef-e465933c5db2.png)

2021-05-19 00:38 UTC, MingboPeng requested changes
Thanks, please see my above comments

2021-05-26 21:37 UTC, MingboPeng commented
Hi @tymokvo please let me know if you need more info to fix this issue. Thanks.

2021-05-27 17:14 UTC, tymokvo commented
Hi @MingboPeng so, just to clarify, `RoleEnum` needs to be in `openapi_inheritance.json` in the same way that (e.g.) `OrganizationRoleEnum` is?

2021-05-27 21:12 UTC, mostaphaRoudsari commented
Hi @tymokvo, Yes all the Enums should show up under that list

2021-08-13 15:54 UTC, MingboPeng commented
Just to repot the new SortEnum is also missing.

2021-10-07 15:19 UTC, tymokvo commented
I think this is closed by https://github.com/pollination/pollination-server/pull/290, closing. Re-open if not.

2021-10-07 15:19 UTC, closed without merging